export const studioRu = {
  'nav.pricing':'Тарифы',
  'globe.label':'Покрутить глобус. Перетащите или используйте клавиши со стрелками.',
  'pricing.label':'Сайт под вашу задачу',
  'pricing.title1':'Разные задачи.',
  'pricing.title2':'Понятная точка старта.',
  'pricing.intro':'От первой идеи до работающего сайта. Выберите подходящий формат — я возьму на себя структуру, дизайн и разработку.',
  'price.cta':'Обсудить формат',
  'price.landing.name':'Лендинг',
  'price.landing.purpose':'Одно предложение. Ясный следующий шаг.',
  'price.landing.amount':'от 65 000 ₽',
  'price.landing.description':'Рассказать об услуге, продукте или запуске и превратить интерес в обращение.',
  'price.landing.f1':'Одна страница, до 8 блоков',
  'price.landing.f2':'Структура предложения и форма заявки',
  'price.landing.f3':'Адаптивный дизайн и лёгкая анимация',
  'price.company.name':'Сайт компании',
  'price.company.purpose':'Помочь понять бизнес и выбрать вас.',
  'price.company.amount':'от 140 000 ₽',
  'price.company.description':'Представить компанию, объяснить услуги и показать, чем отличается ваша работа.',
  'price.company.f1':'До 5 уникальных страниц',
  'price.company.f2':'Услуги, проекты и контакты',
  'price.company.f3':'CMS для новостей или проектов',
  'price.catalog.name':'Каталог',
  'price.catalog.purpose':'Упростить выбор и запрос цены.',
  'price.catalog.amount':'от 190 000 ₽',
  'price.catalog.description':'Систематизировать ассортимент, чтобы посетитель мог изучить его и оставить запрос.',
  'price.catalog.f1':'Категории, фильтры и карточки',
  'price.catalog.f2':'CMS и первые 20 позиций',
  'price.catalog.f3':'Заявки без онлайн-оплаты',
  'price.shop.name':'Интернет-магазин',
  'price.shop.purpose':'Провести от знакомства до покупки.',
  'price.shop.amount':'от 260 000 ₽',
  'price.shop.description':'Продумать путь покупателя: от выбора товара до корзины, оплаты и оформления заказа.',
  'price.shop.f1':'Каталог, корзина и оформление',
  'price.shop.f2':'Подключение одного платёжного сервиса',
  'price.shop.f3':'Первые 20 товаров',
  'pricing.included':'В каждом формате',
  'pricing.baseline':'Мобильная версия, базовая SEO-настройка, запуск и инструкция по управлению сайтом.',
  'pricing.note':'Цены — от указанной суммы за состав выше. Объём, сроки и итоговую стоимость согласуем до начала. Домен, хостинг, тариф платформы, платные сервисы и большой импорт контента оплачиваются отдельно.',
  'stack.label':'Человек и инструменты',
  'stack.title1':'За сайтом — я.',
  'stack.title2':'Вокруг — мой стек.',
  'stack.bio':'Я Фёдор Попов, дизайнер и веб-разработчик. Живу в Черногории и работаю с проектами из разных стран. Сам продумываю структуру, создаю дизайн и собираю сайт.',
  'stack.approach':'Выбираю инструменты под задачу: быстрый запуск на платформе или разработка с нуля, если проекту нужна особая логика.',
  'stack.design':'Дизайн',
  'stack.platforms':'Платформы',
  'stack.code':'Код',
  'stack.design.detail':'Внутренняя орбита · визуальный язык',
  'stack.platforms.detail':'Средняя орбита · сборка и контент',
  'stack.code.detail':'Внешняя орбита · разработка',
  'stack.hint':'Наведите, чтобы остановить. Нажмите на инструмент, чтобы узнать больше.',
  'stack.stage':'Интерактивный стек: три орбиты. Перетаскивайте по горизонтали или используйте стрелки.',
  'stack.center':'Фёдор',
  'stack.initial':'Нажмите на любой инструмент',
  'stack.initialText':'Расскажу, где он помогает в работе над сайтом.',
  'contact.selectedLabel':'Выбранный формат',
  'contact.clear':'Убрать выбор',
};

export const stackTools = [
  {id:'figma',name:'Figma',group:'design',ru:'Прототипы, интерфейсы и система компонентов до начала разработки.',en:'Prototypes, interfaces, and a component system before development.'},
  {id:'photoshop',name:'Photoshop',group:'design',ru:'Обработка фотографий, ретушь и подготовка изображений для сайта.',en:'Photo editing, retouching, and image preparation for the website.'},
  {id:'illustrator',name:'Illustrator',group:'design',ru:'Векторная графика, знаки и иллюстрации, чёткие на любом экране.',en:'Vector graphics, marks, and illustrations that stay sharp on every screen.'},
  {id:'framer',name:'Framer',group:'platforms',ru:'Выразительные сайты с анимацией и удобным визуальным редактированием.',en:'Expressive websites with animation and convenient visual editing.'},
  {id:'tilda',name:'Tilda',group:'platforms',ru:'Лендинги и контентные страницы с удобной передачей заказчику.',en:'Landing pages and content-led websites with a straightforward handover.'},
  {id:'wordpress',name:'WordPress',group:'platforms',ru:'Контентные сайты, каталоги и магазины с гибкой системой управления.',en:'Content websites, catalogs, and stores with flexible content management.'},
  {id:'html5',name:'HTML',group:'code',ru:'Понятная структура страницы, семантика и доступность контента.',en:'Page structure, semantic markup, and accessible content.'},
  {id:'css3',name:'CSS',group:'code',ru:'Адаптивные макеты, визуальные детали и плавные переходы.',en:'Responsive layouts, visual detail, and smooth transitions.'},
  {id:'javascript',name:'JavaScript',group:'code',ru:'Логика интерфейса и интерактивность — в том числе эти орбиты.',en:'Interface logic and interactivity — including these orbits.'},
  {id:'typescript',name:'TypeScript',group:'code',ru:'Типизация для более предсказуемой работы сложных интерфейсов.',en:'Types that make complex interface code more predictable.'},
  {id:'react',name:'React',group:'code',ru:'Переиспользуемые компоненты и интерфейсы с динамическими данными.',en:'Reusable components and interfaces with dynamic data.'},
  {id:'nextjs',name:'Next.js',group:'code',ru:'Многостраничные React-проекты, маршрутизация и серверная логика.',en:'Multi-page React projects, routing, and server-side logic.'},
  {id:'tailwindcss',name:'Tailwind CSS',group:'code',ru:'Единая система стилей и быстрая сборка адаптивных компонентов.',en:'Consistent styling and efficient responsive component development.'},
];
