import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { templateTerms } from './template-terms.mjs';

export const privacyVersion = '2026-10-06';
const operator = 'Попов Федор Владимирович';
const email = 'fedorpopov7@yandex.ru';
const documents = {
  ru: {
    terms: templateTerms.ru,
    privacy: { title: 'Политика конфиденциальности', sections: [
      ['Оператор и связь', `Персональные данные посетителей PopovWeb обрабатывает ${operator}, Российская Федерация. По вопросам обработки данных, доступа, исправления и удаления: ${email}.`],
      ['Какие данные используются', 'В форме заявки вы указываете имя и один контакт для ответа: имя пользователя Telegram, номер телефона WhatsApp или адрес электронной почты. По желанию можно добавить описание проекта. Также передаются выбранный формат сайта, язык формы и подтверждение согласия. Не указывайте паспортные, платёжные, медицинские данные и сведения о третьих лицах.'],
      ['Цели и основания', 'Данные заявки нужны, чтобы ответить на обращение, уточнить задачу и обсудить предложение по разработке сайта. Основание обработки заявки — отдельное согласие, которое вы даёте перед отправкой формы. Если заключается договор, необходимые для его исполнения сведения обрабатываются на соответствующем законном основании. Заявка не является подпиской на рекламу.'],
      ['Как обрабатывается заявка', 'Обработка включает получение, запись, систематизацию, хранение, уточнение, использование для ответа и удаление. При подключённой форме её серверный обработчик передаёт заявку оператору через Telegram Bot API: имя, выбранный контакт, сообщение, формат проекта и сведения о согласии. Заявка не публикуется на сайте. Передача в Telegram означает использование стороннего сервиса; его собственная политика доступна по адресу https://telegram.org/privacy. Для обработки обращений применяются требования законодательства РФ, включая требования к локализации и трансграничной передаче данных.'],
      ['Сроки обработки', 'Данные используются до завершения ответа и обсуждения обращения либо до отзыва согласия, если нет другого законного основания для продолжения обработки. При заключении договора необходимые сведения хранятся в сроки, обусловленные его исполнением и требованиями закона. После достижения цели или отзыва согласия сведения удаляются в предусмотренные законом сроки.'],
      ['Технические данные и хранение в браузере', 'Для выдачи страниц и защиты от злоупотреблений инфраструктура хостинга может обрабатывать IP-адрес, время запроса, адрес страницы и сведения о браузере. Настройки темы и языка сохраняются в localStorage вашего браузера. При переключении языка черновик заявки временно переносится через sessionStorage текущей вкладки и удаляется из этого хранилища при открытии следующей языковой версии. Неотправленный черновик не направляется оператору.'],
      ['Яндекс Метрика и Вебмастер', 'В текущей версии счётчик Яндекс Метрики не подключён. Планируется анализ посещаемости с помощью Метрики. Перед её подключением эта политика будет обновлена с описанием действующих настроек, состава данных и сроков хранения; будет предусмотрен выбор посетителя в отношении аналитики. Вебмастер планируется использовать для управления представлением сайта в поиске; сам по себе он не добавляет счётчик посещений. Политика Яндекса: https://yandex.ru/legal/confidential/.'],
      ['Ваши права', `Вы можете запросить информацию об обработке своих данных, их уточнение, блокирование или удаление и отозвать согласие письмом на ${email}. Укажите контакт, использованный в заявке, чтобы можно было найти обращение; не отправляйте копии документов без необходимости. Отказ от передачи данных через форму не мешает просматривать сайт. За защитой прав можно обратиться в Роскомнадзор или суд.`],
      ['Защита и изменения', 'Доступ к заявкам предназначен для оператора и лиц, законно участвующих в их обработке. Передача формы должна выполняться по HTTPS, токен Telegram-бота хранится только на сервере. Изменения условий обработки отражаются в новой редакции этого документа. Текущая редакция: 6 октября 2026 года.'],
    ] },
    consent: { title: 'Согласие на обработку персональных данных', sections: [
      ['Кому и для чего', `Отмечая отдельный чекбокс и отправляя заявку, я даю ${operator} (Российская Федерация, ${email}) согласие на обработку указанных мной данных для ответа на обращение и обсуждения разработки сайта.`],
      ['Состав данных и действия', 'Согласие относится к имени, выбранному контактному адресу (Telegram, WhatsApp или email), описанию проекта, выбранному формату, языку обращения и сведениям о предоставлении согласия. Допускаются получение, запись, систематизация, накопление, хранение, уточнение, использование для ответа и удаление, с применением средств автоматизации и без них. При работающей интеграции заявка передаётся оператору через Telegram Bot API. Публичное распространение и рекламная рассылка этим согласием не разрешаются.'],
      ['Срок действия и отзыв', `Согласие действует до достижения цели обращения или его отзыва. Отозвать его можно письмом на ${email}. После отзыва обработка прекращается и данные удаляются в предусмотренные законом сроки, кроме случаев, когда есть иное законное основание для продолжения обработки. Версия согласия: ${privacyVersion}.`],
    ] },
  },
  en: {
    terms: templateTerms.en,
    privacy: { title: 'Privacy policy', sections: [
      ['Controller and contact', `Fedor Vladimirovich Popov (${operator}), Russian Federation, operates PopovWeb and handles enquiries. Contact for privacy requests: ${email}.`],
      ['Enquiry data', 'The form requests your name and one reply channel: a Telegram username, WhatsApp telephone number or email address. A project description is optional. The selected website format, form language and consent confirmation are also submitted. Please do not include identity documents, payment or health information, or third-party personal data.'],
      ['Purpose and basis', 'Enquiry data is used to respond, clarify the project and discuss a website development proposal, based on the separate consent given before submission. Information required for a subsequent contract may be processed on the applicable legal basis. An enquiry does not subscribe you to advertising.'],
      ['Handling and recipients', 'Processing includes receipt, recording, organisation, storage, correction, use for responding and deletion. When the form is connected, its server sends the name, contact, message, project format and consent information to the controller through the Telegram Bot API. Enquiries are not published on the website. Telegram is a third-party service with its own policy at https://telegram.org/privacy. Applicable Russian requirements, including data localisation and cross-border transfer requirements, apply to enquiry processing.'],
      ['Retention', 'Enquiry data is used until the response and related discussion are completed or consent is withdrawn, unless another legal basis permits continued processing. Contract-related information is retained as required for performance and legal obligations. Data is deleted within the applicable statutory periods when the purpose ends or consent is withdrawn.'],
      ['Technical data and browser storage', 'Hosting infrastructure may process an IP address, request time, page address and browser information to deliver pages and prevent abuse. Theme and language preferences are stored in browser localStorage. Switching language temporarily transfers a form draft through the tab’s sessionStorage; this storage entry is removed on arrival at the next language version. Unsubmitted drafts are not sent to the controller.'],
      ['Yandex services', 'Yandex Metrica is not enabled in this version. Visitor analytics using Metrica is planned. Before activation, this policy will be updated with the actual settings, data and retention terms, and visitors will be given an analytics choice. Yandex Webmaster is planned for search visibility management; it does not by itself add a visitor tracking tag. Yandex policy: https://yandex.ru/legal/confidential/.'],
      ['Your requests', `You can request information, correction, blocking or deletion of your data and withdraw consent by emailing ${email}. Include the contact used in your enquiry to help locate it, without unnecessary identity documents. Browsing the site does not require submitting the form. You may seek protection of your rights from the competent authority or a court.`],
      ['Protection and updates', 'Enquiry access is intended for the controller and persons lawfully involved in processing. The form must use HTTPS and the bot token must remain on the server. Changes to processing will be reflected in a new policy version. Updated: 6 October 2026.'],
    ] },
    consent: { title: 'Consent to personal data processing', sections: [
      ['Controller and purpose', `By selecting the separate checkbox and submitting an enquiry, I consent to Fedor Vladimirovich Popov (${operator}, Russian Federation, ${email}) processing the information I provide to respond and discuss website development.`],
      ['Data and operations', 'This covers my name, selected Telegram/WhatsApp/email contact, project description, selected format, form language and consent record. Processing includes receipt, recording, organisation, storage, correction, use for responding and deletion, with or without automation. A connected integration sends the enquiry to the controller through the Telegram Bot API. This consent does not authorise public disclosure or advertising messages.'],
      ['Duration and withdrawal', `Consent lasts until the purpose is fulfilled or I withdraw it by emailing ${email}. Processing then stops and data is deleted within applicable legal periods unless another legal basis applies. Consent version: ${privacyVersion}.`],
    ] },
  },
};
const escape = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const markup = text => escape(text).replace(/https:\/\/[^\s]+(?=\s|$)/g, url => { const clean=url.replace(/\.$/,''); return `<a href="${clean}">${clean}</a>${url.endsWith('.')?'.':''}`; }).replaceAll(email, `<a href="mailto:${email}">${email}</a>`);
export async function buildLegal(root) {
  const dir=resolve(root,'documents'); await mkdir(dir,{recursive:true});
  for (const locale of ['ru','en']) for (const kind of ['privacy','consent','terms']) {
    const doc=documents[locale][kind], name=`${kind}-${locale}`;
    const version=doc.version || privacyVersion;
    const plain=[doc.title,`PopovWeb · ${version}`,...doc.sections.flatMap(([h,p])=>['',h,p])].join('\n');
    await writeFile(resolve(dir,`${name}.txt`),plain+'\n');
    await writeFile(resolve(dir,`${name}.html`),`<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, follow"><title>${doc.title} — PopovWeb</title><link rel="icon" href="../assets/favicon.svg?v=vw-3"><link rel="stylesheet" href="../fonts.css"><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#1b1d1a;color:#f4f4f0;font:16px/1.75 Manrope,system-ui,sans-serif}main{max-width:860px;margin:auto;padding:40px 24px 80px}nav{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;border-bottom:1px solid #393c36;padding-bottom:24px}a{color:inherit;text-underline-offset:5px}a:hover{color:#fc6833}a:focus-visible{outline:2px solid #fc6833;outline-offset:5px}header{padding:44px 0 24px}h1{font-size:clamp(30px,6vw,48px);line-height:1.18;letter-spacing:-.04em;font-weight:500;margin:10px 0 22px}h2{font-size:22px;font-weight:500;margin:32px 0 10px}p{margin:0 0 16px;overflow-wrap:anywhere;color:#c6c8bf}.date{color:#fc6833;font-size:13px}@media print{:root{color-scheme:light}body{background:#fff;color:#111}p{color:#222}nav{display:none}main{max-width:none;padding:0}h2{break-after:avoid}a{color:inherit}.date{color:#333}}</style></head><body><main><nav><a href="${locale==='ru'?'../':'../en/'}">← PopovWeb</a><a href="${name}.txt" download>${locale==='ru'?'Скачать документ (.txt)':'Download document (.txt)'}</a><a href="${kind}-${locale==='ru'?'en':'ru'}.html" hreflang="${locale==='ru'?'en':'ru'}">${locale==='ru'?'English':'Русский'}</a></nav><header><div class="date">${version}</div><h1>${doc.title}</h1></header>${doc.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${markup(p)}</p></section>`).join('')}<p><a href="${kind==='privacy'?'consent':'privacy'}-${locale}.html">${documents[locale][kind==='privacy'?'consent':'privacy'].title}</a></p></main></body></html>`);
  }
}
