// Product terms approved for publication: refunds for access problems or substantial defects,
// with mandatory consumer rights preserved. Keep RU and EN substantively equivalent.
const email = 'fedorpopov7@yandex.ru';
export const templateTerms = {
  ru: {
    version: '2026-10-08',
    title: 'Условия покупки и использования шаблонов',
    sections: [
      ['1. О документе и авторе', `Эти условия относятся к покупке и использованию цифровых Framer-шаблонов PopovWeb, включая VELORA. Автор и контакт по вопросам продукта — Попов Федор Владимирович (Fedor Popov), ${email}. Объём и стоимость индивидуальной разработки сайта согласовываются отдельно. Перед оплатой ознакомьтесь с этими условиями, описанием выбранного шаблона и условиями оформления заказа.`],
      ['2. Что вы приобретаете', 'Вы приобретаете лицензию на редактируемый цифровой шаблон для Framer. Состав страниц, функций и материалов определяется описанием конкретного продукта на момент покупки. Для работы нужен аккаунт Framer. Тариф Framer, домен, платные шрифты и сторонние сервисы оплачиваются отдельно, если в описании прямо не указано иное. Индивидуальная настройка, написание текстов и создание контента не входят в стоимость шаблона.'],
      ['3. Лицензия и допустимое использование', 'Одна покупка предоставляет неисключительную лицензию на использование и изменение шаблона в одном конечном сайте или проекте, в том числе коммерческом. Для другого сайта или проекта требуется отдельная лицензия. Авторские права на исходный шаблон сохраняются за автором. Для продукта, приобретённого через Framer Marketplace, также действует лицензия платного контента из Framer Community Terms: https://www.framer.com/legal/community-terms/1.0.'],
      ['4. Ограничения и сторонние материалы', 'Нельзя перепродавать, публиковать, раздавать или передавать другим лицам исходный шаблон либо ссылку для его копирования; предлагать его как собственный шаблон, набор компонентов или конкурирующий цифровой продукт. Нельзя удалять уведомления об авторских правах из исходных материалов. Изображения, шрифты и другие сторонние материалы регулируются лицензиями их правообладателей. Перед публикацией своего сайта проверьте права на используемый контент и при необходимости замените демонстрационные материалы.'],
      ['5. Цена и оплата', 'Цена и валюта указаны в карточке продукта; итоговая сумма с применимыми налогами и сборами показывается перед подтверждением оплаты. Покупка шаблона является разовым платежом, если в предложении прямо не указана подписка. При оплате через Creem сервис выступает продавцом по платёжной операции (Merchant of Record), обрабатывает оплату и возвраты. К этой операции применяются условия Creem для покупателей: https://www.creem.io/buyer-terms.'],
      ['6. Получение шаблона', `После успешной оплаты доступ предоставляется цифровым способом: через ссылку для копирования проекта в Framer и инструкции на странице подтверждения заказа или в письме на email, указанный при покупке. Сохраните подтверждение покупки и не публикуйте ссылку доступа. Если ссылка отсутствует, не открывается или не позволяет получить оплаченный шаблон, напишите на ${email}, указав номер заказа и email покупки.`],
      ['7. Поддержка', `По вопросам доступа, использования поставленного шаблона и обнаруженных ошибок обращайтесь на ${email}. Опишите проблему и, если возможно, приложите снимок экрана без паролей и платёжных данных. Поддержка помогает разобраться с работой шаблона в заявленном составе. Доработки под конкретный бизнес, новые функции и интеграции согласовываются отдельно. Обязательные права покупателя в отношении качества цифрового продукта сохраняются.`],
      ['8. Возвраты', `Возврат предусмотрен при непредоставлении оплаченного доступа, а также при существенных дефектах или несоответствии описанию, которые не удаётся устранить в разумный срок. Для обращения напишите на ${email}, указав номер заказа, email покупки и описание проблемы. Мы проверим обращение, поможем восстановить доступ или устранить проблему; при наличии оснований оформим возврат через Creem. Безусловный возврат из-за изменения планов или предпочтений не предлагается, кроме случаев, когда он обязателен по закону. После возврата за шаблон его использование по возвращённой лицензии необходимо прекратить.`],
      ['9. Обязательные права покупателя', 'Эти условия не ограничивают права потребителя, которые нельзя исключить договором, включая предусмотренные законом права при непредоставлении или ненадлежащем качестве цифрового контента. Сам по себе цифровой формат не отменяет такие права. Если применимое право допускает утрату права на отказ при немедленном предоставлении цифрового контента, необходимые отдельные согласие и подтверждение должны быть получены при оформлении заказа; простое посещение этой страницы их не заменяет.'],
      ['10. Ответственность и изменения', 'Покупатель отвечает за собственные изменения шаблона, размещённый контент и соблюдение прав третьих лиц. PopovWeb не гарантирует определённый объём продаж, трафик или позиции в поиске. Работа платформы Framer и сторонних сервисов регулируется их собственными условиями; это не отменяет наших обязательств по поставленному продукту. Новая редакция этих условий применяется к последующим покупкам и не уменьшает права по уже оплаченному заказу. По вопросам и спорным ситуациям сначала свяжитесь с автором по указанному email.'],
    ],
  },
  en: {
    version: '2026-10-08',
    title: 'Terms of Service',
    sections: [
      ['1. Scope and creator', `These terms cover the purchase and use of PopovWeb digital Framer templates, including VELORA. The creator and product contact is Fedor Vladimirovich Popov (Fedor Popov), ${email}. Custom website development has a separately agreed scope and price. Before paying, review these terms, the selected template’s description and the checkout terms.`],
      ['2. What you purchase', 'You purchase a licence to an editable digital template for Framer. The pages, features and materials included are those described for the specific product at the time of purchase. A Framer account is required. Framer plans, domains, paid fonts and third-party services are charged separately unless expressly included in the product description. Bespoke setup, copywriting and content creation are not included in the template price.'],
      ['3. Licence and permitted use', 'Each purchase grants a non-exclusive licence to use and modify the template in one final website or project, including a commercial project. Another website or project requires a separate licence. The creator retains copyright in the original template. Products bought through Framer Marketplace are also subject to the paid-content licence in the Framer Community Terms: https://www.framer.com/legal/community-terms/1.0.'],
      ['4. Restrictions and third-party assets', 'You must not resell, publish, distribute or share the original template or its duplication link, or offer it as your own template, component pack or competing digital product. Do not remove copyright notices from the source materials. Images, fonts and other third-party assets remain subject to their owners’ licences. Before publishing your website, check your rights to the content you use and replace demonstration assets where necessary.'],
      ['5. Pricing and payment', 'The product listing states the price and currency. The final total, including applicable taxes and charges, is shown before payment confirmation. A template purchase is a one-time payment unless the offer expressly states that it is a subscription. For purchases processed through Creem, Creem acts as Merchant of Record and handles payment and refunds. Its Buyer Terms apply to the transaction: https://www.creem.io/buyer-terms.'],
      ['6. Digital delivery', `After successful payment, access is provided digitally through a link to duplicate the project into Framer and instructions on the order confirmation page or in an email sent to the purchase address. Keep your purchase confirmation and do not publish the access link. If the link is missing, broken or does not provide the purchased template, contact ${email} with your order number and purchase email.`],
      ['7. Support', `For access issues, questions about the supplied template or bugs, contact ${email}. Describe the issue and, where useful, attach a screenshot without passwords or payment details. Support helps you use the template’s advertised features. Business-specific customisation, new features and integrations require a separate agreement. Mandatory buyer rights concerning the quality of digital products are preserved.`],
      ['8. Refunds', `Refunds are available if paid access is not provided, or if a substantial defect or material mismatch with the product description cannot be resolved within a reasonable time. Contact ${email} with your order number, purchase email and a description of the issue. We will investigate and help restore access or remedy the issue; where a refund is due, it will be processed through Creem. Unconditional refunds for a change of plans or personal preference are not offered, except where required by law. After a template refund, you must stop using it under the refunded licence.`],
      ['9. Mandatory consumer rights', 'These terms do not limit consumer rights that cannot be excluded by contract, including statutory remedies for failure to supply or lack of conformity of digital content. A product’s digital format does not, by itself, remove those rights. Where applicable law permits loss of a withdrawal right when digital content is supplied immediately, any required separate consent and acknowledgement must be obtained at checkout; merely visiting this page does not provide them.'],
      ['10. Responsibilities and changes', 'You are responsible for your modifications, published content and respect for third-party rights. PopovWeb does not promise a particular level of sales, traffic or search rankings. Framer and third-party services operate under their own terms; this does not remove our obligations for the supplied product. Updated terms apply to future purchases and do not reduce your rights under an already paid order. Please first contact the creator at the email above with any questions or disputes.'],
    ],
  },
};
